urdfFilePath: C:/Users/chiha/OneDrive/Bureau/Dynamium/dynamic-identification/exemple/kinova/gen3.urdf
robot_params:
  base_frame: world
  tool_frame: bracelet_link
  friction : viscous
  has_joint_offset : True
  offset   : [3.92e-1, 1.37, 3.26e-1, -1.02e-1, -2.88e-2, 1.27e-1]
identification:
  dataFilePath : C:/Users/chiha/OneDrive/Bureau/Dynamium/dynamic-identification/data/kinova/identification_data/blast_traj.csv
  problem_params:
    has_friction         : True
    has_stiffness        : True
    has_backlash         : False
    has_actuator         : True
    has_ external_forces : False
simulation:
  time_step : 0.001
  sampling_frequency : 1000
  max_samples_num : 1940
optimisation:
  pso:
    W  : 0.5
    c1 : 0.8
    c2 : 0.9 
    r1: -0.2
    r2: 1.1
  cmaes:
stiffness_params: [0.25, 0.26, 0.369, 0.125, 0.258, 0.123, 0.11] 
actuator_params:
  kt: [0.81, 0.11, 0.11, 0.11, 0.11, 0.11, 0.11]
  Imax : [5, 5, 5, 5, 5, 5, 5]
  Tmax : [17, 17, 17, 17, 17, 17, 17]
  inertia : [0.558, 0.558, 0.558, 0.558, 0.558, 0.558, 0.558]
  damping : [0.014, 0.014, 0.014, 0.014, 0.014, 0.014, 0.14]
  Ta : [0.22, 0.22, 0.22, 0.22, 0.22, 0.22, 0.22]
  Tb: [0.21, 0.21, 0.21, 0.21, 0.21, 0.21, 0.21]
  Tck : [[0.015, 0.018, 0.023, 0.0201, 0.0147],
    [0.015, 0.018, 0.023, 0.0201, 0.0147],
    [0.015, 0.018, 0.023, 0.0201, 0.0147],
    [0.015, 0.018, 0.023, 0.0201, 0.0147],
    [0.015, 0.018, 0.023, 0.0201, 0.0147],
    [0.015, 0.018, 0.023, 0.0201, 0.0147],
    [0.015, 0.018, 0.023, 0.0201, 0.0147]]
friction_params:
  maxwellSlip:
    n: 3
    k: [1.1, 1.2, 0.5] 
    c: [1.2, 1.5, 0.3]
    sigma0: [1.25, 1, 0.5, 0.25, 0.2, 0.3, 1.6]
  viscous:
    Fc : [0.025, 0.025, 0.05, 0.036, 0.058, 0.058, 0.025]
    Fs : [0.05, 0.026, 0.036, 0.02, 0.025, 0.025, 0.01]
  lugre:
    sigma0: [0.02, 0.5, 0.2, 0.3, 0.3, 0.258, 0.147]
    sigma1: [0.2, 0.5, 0.2, 0.3, 0.3, 0.258, 0.147]
    sigma2: [0.2, 0.15, 0.12, 0.3, 0.3, 0.258, 0.147]
    Fc    : [-1.25, 1.25, 2.5, 3.36, 1.58, 2.58, 4.25]
    Fs    : [2.52, 1.26, 0.36, 0.2, 0.25, 1.25, 0.01]
  dahl:
    sigma0 : [100, 100, 100, 100, 100, 100, 100]
    Fs : [15, 15, 15, 15, 15, 15, 15]
noise_params:
  gauss: 
    mean : 0
    stdv : 0.1
  poisson:
    lamda : 1
state_space_params:
    poles : [0.8, 0.51, 0.53, 0.57, 0.51, 0.8, 0.85,  0.5, 0.25, 0.55, 0.65, 0.75, 0.32, 0.85]
